#ifndef FLASHINTERFACE_H
#define FLASHINTERFACE_H

#include "structs.h"


uint FlashInterface_FreeCombat_Max(int);
uint FlashInterface_FreeCombat_PrepCreatureName(int,int *);
uint FlashInterface_FreeCombat_Prep(void);
uint FlashInterface_FreeCombat_Respawn(goGameObject *);
uint FlashInterface_FreeCombat_ShouldAttack(goGameObject *);
uint FlashInterface_FreeCombat_GetCreature(int,int *,int *);
uint FlashInterface_FreeCombat_CreatureCount(void);
uint FlashInterface_BonusScroll_BonusStrings(int,char **);
uint FlashInterface_BonusScroll_Update(int);
uint FlashInterface_BonusScroll_Command(int);
uint FlashInterface_BonusScroll_Init(void);
uint FlashInterface_MoveScroll_MoveStrings(int,char **,char **);
uint FlashInterface_MoveScroll_Update(int);
uint FlashInterface_MoveScroll_CheckMove(int,int *,int *,int *);
uint FlashInterface_MoveScroll_ShouldDisplay(int);
uint FlashInterface_MoveScroll_FindHeaderIdx(int);
uint FlashInterface_MoveScroll_Command(int);
uint FlashInterface_MoveScroll_IsMoveNew(int);
uint FlashInterface_MoveScroll_SetMoveSeen(int);
uint FlashInterface_MoveScroll_Init(void);
uint FlashInterface_RemSO(F_SpriteInstance *);
uint FlashInterface_AnimSO(char const *,int,float,float);
uint FlashInterface_AddSO(char const *);
uint FlashInterface_SO_CB(F_SpriteInstance *,F_SpriteInstance_CBCode,void const *);
uint FlashInterface_SO_Setup(renGROB *);
uint FlashInterface_AnimateGO(char const *,char const *);
uint FlashInterface_SetStateData(void const *);
uint FlashInterface_GetStateData(void *);
uint FlashInterface_PromptButton(uint);
uint FlashInterface_RegisterPromptButtons(renFlashClient *);
uint FlashInterface_ClearHUD(int);
uint FlashInterface_HitCounter(int,int,int,int);
uint FlashInterface_DoCommend(int,float);
uint FlashInterface_MsgMenuPause(int);
uint FlashInterface_DoMenu(int,int);
uint FlashInterface_StopFlashTypeOn(void);
uint FlashInterface_TellFlashTypeOn(int,int);
uint FlashInterface_DoMsgPage(void);
uint FlashInterface_DoMsg(int,float,int);
uint FlashInterface_GetMsgLine(int,int,char const **);
uint FlashInterface_FindMsg(int,char const ***,int *);
uint FlashInterface_CmpMsgs(void const *,void const *);
uint FlashInterface_ParseMsgFile(int,char *,int,int);
uint FlashInterface_ReadMsgText(void);
uint FlashInterface_CancelMsg(int);
uint FlashInterface_PerFrame(void);
uint FlashInterface_SendEvtMsgDone(int);
uint FlashInterface_MsgMenuCheck(void);
uint FlashInterface_SimKeyEvent(void);
uint FlashInterface_CommandResult(int);
uint FlashInterface_SetCamera(char const *);
uint FlashInterface_Command(char const *,char const *,int);
uint FlashInterface_FloatArg(char const **,float);
uint FlashInterface_IntArg(char const **,int);
uint FlashInterface_StringArg(char const **,char *);
uint FlashInterface_ResetSettableStrings(void);
uint FlashInterface_StopAllSounds(void);
uint FlashInterface_PlaySound(int,char const *);
uint FlashInterface_SetVariable(char const *,int,void const *);
uint FlashInterface_GetVariable(char const *,int *,void **);
uint FlashInterface_LookupVariable(char const *);
uint FlashInterface_GetCurrentSpriteInstance(void);
uint FlashInterface_FindClient(char const *);
uint FlashInterface_RemoveClient(char const *);
uint FlashInterface_AddClient(char const *);
uint FlashInterface_FindMemoryCardImages(char const *);
uint FlashInterface_MemoryCardClearImages(void);
uint FlashInterface_MemoryCardSetImages(int *);
uint FlashInterface_MemoryCardImageWadContext(wadContext *);
uint FlashInterface_ReplaceTexture(F_Shape *,renTexture *);
uint FlashInterface_GrabTexture(F_Shape *);
uint FlashInterface_FindDynamicShapes(renFlashClient *);
uint FlashInterface_ResetShortTerm(void);
uint FlashInterface_ResetVars(void);
uint FlashInterface_OneTimeSetup(void);
uint FlashInterface_Destructor_FlashInterface(void);
uint FlashInterface_FlashInterface(void);
uint FlashInterface_AddVar(int,char const *,int,void *,void (FlashInterface_*)(FlashInterface *,FlashInterface_fvEntry const *));
uint FlashInterface_HashFindAvailable(char const *);
uint FlashInterface_HashFind(char const *);
uint FlashInterface_Hash(char const *);
uint FlashInterface_SetSoundMode(int);
uint FlashInterface_SetProgressiveScan(int);
uint FlashInterface_SetWideScreen(int);
uint FlashInterface_SetVibration(int);
uint FlashInterface_SetSoundVolume(int);
uint FlashInterface_SetMusicVolume(int);
uint FlashInterface_SetZoneVars(int);
uint FlashInterface_SF_Zone_Choice(FlashInterface_fvEntry const *);
uint FlashInterface_SF_FOV(FlashInterface_fvEntry const *);
uint FlashInterface_SF_OverUnder(FlashInterface_fvEntry const *);
uint FlashInterface_SF_DropShadowOffset(FlashInterface_fvEntry const *);
uint FlashInterface_SF_DropShadowColor(FlashInterface_fvEntry const *);
uint FlashInterface_SF_SoundMode(FlashInterface_fvEntry const *);
uint FlashInterface_SF_ProgressiveScan(FlashInterface_fvEntry const *);
uint FlashInterface_SF_WideScreen(FlashInterface_fvEntry const *);
uint FlashInterface_SF_Vibration(FlashInterface_fvEntry const *);
uint FlashInterface_SF_Volume(FlashInterface_fvEntry const *);
uint FlashInterface_SF_Sound(FlashInterface_fvEntry const *);
uint FlashInterface_msgFile;
uint FlashInterface_vtbl;


#endif