#ifndef HFSM_PEGASUSENEMY_H
#define HFSM_PEGASUSENEMY_H

#include "structs.h"


uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SDESTROYAI_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SFADE_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SFlight_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SFlight_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SSwarm_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SSwarm_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SLockedOn_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SLockedOn_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SPatrol_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SPatrol_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SInitialMove_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SInitialMove_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SDESTROYAI_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SDESTROYAI_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SFADE_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SFADE_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SPREPDIE_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SPREPDIE_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SFlight_SFlight(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SSwarm_SSwarm(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SLockedOn_SLockedOn(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SPatrol_SPatrol(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SInitialMove_SInitialMove(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SDESTROYAI_SDESTROYAI(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SFADE_SFADE(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SPREPDIE_SPREPDIE(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SStart(HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SFlight_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SSwarm_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SLockedOn_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SPatrol_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SInitialMove_EntryCode(bhvrHFSMClient *,goPegasusAI *,goEvent const *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_hfsmPegasusEnemy(void);
uint HFSM_PegasusEnemy_HFSMCreator_GetDataSize(void);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_Destructor_hfsmPegasusEnemy(void);
uint HFSM_PegasusEnemy_HFSMCreator_HFSMCreator(void);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy___dl(void *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_Allocate(wadContext *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_GetStartState(bhvrHFSMClient *,goEvent const *);
uint HFSM_PegasusEnemy_HFSMCreator_GetDependantClass(int);
uint HFSM_PegasusEnemy_HFSMCreator_GetNumDependantClasses(void);
uint HFSM_PegasusEnemy_HFSMCreator_GetName(void);
uint HFSM_PegasusEnemy_HFSMCreator_Create(void);
uint HFSM_PegasusEnemy_GetParam(bhvrHFSMClient *);
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_sm_hfsmPegasusEnemyMultiPool;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SInitialMove_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SPatrol_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SLockedOn_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SSwarm_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_SFlight_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SStart_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SPREPDIE_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SFADE_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_SDESTROYAI_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_SPegasusEnemy_vtbl;
uint HFSM_PegasusEnemy_HFSMCreator_vtbl;
uint HFSM_PegasusEnemy_hfsmPegasusEnemy_vtbl;


#endif