#ifndef FLASHINTERFACE_H
#define FLASHINTERFACE_H

#include "structs.h"

uint FlashInterface_FreeCombat_Max(int);
uint FlashInterface_FreeCombat_PrepCreatureName(int,int *);
uint FlashInterface_FreeCombat_Prep(void);
// uint FlashInterface_FreeCombat_Respawn(goGameObject *);
// uint FlashInterface_FreeCombat_ShouldAttack(goGameObject *);
uint FlashInterface_FreeCombat_GetCreature(int,int *,int *);
uint FlashInterface_FreeCombat_CreatureCount(void);
uint FlashInterface_BonusScroll_BonusStrings(int,char **);
uint FlashInterface_BonusScroll_Update(int);
uint FlashInterface_BonusScroll_Command(int);
uint FlashInterface_BonusScroll_Init(void);
uint FlashInterface_MoveScroll_MoveStrings(int,char **,char **);
uint FlashInterface_MoveScroll_Update(int);
uint FlashInterface_MoveScroll_CheckMove(int,int *,int *,int *);
uint FlashInterface_MoveScroll_ShouldDisplay(int);
uint FlashInterface_MoveScroll_FindHeaderIdx(int);
uint FlashInterface_MoveScroll_Command(int);
uint FlashInterface_MoveScroll_IsMoveNew(int);
uint FlashInterface_MoveScroll_SetMoveSeen(int);
uint FlashInterface_MoveScroll_Init(void);
// uint FlashInterface_RemSO(F_SpriteInstance *);
uint FlashInterface_AnimSO(char const *,int,float,float);
uint FlashInterface_AddSO(char const *);
// uint FlashInterface_SO_CB(F_SpriteInstance *,F_SpriteInstance_CBCode,void const *);
// uint FlashInterface_SO_Setup(renGROB *);
uint FlashInterface_AnimateGO(char const *,char const *);
uint FlashInterface_SetStateData(void const *);
uint FlashInterface_GetStateData(void *);
uint FlashInterface_PromptButton(uint);
// uint FlashInterface_RegisterPromptButtons(renFlashClient *);
uint FlashInterface_ClearHUD(FlashInterface *,int);
uint FlashInterface_HitCounter(FlashInterface *,int,int,int,int);
uint FlashInterface_DoCommend(FlashInterface *,int,float);
uint FlashInterface_MsgMenuPause(FlashInterface *,int);
uint FlashInterface_DoMenu(FlashInterface *,int,int);
uint FlashInterface_StopFlashTypeOn(FlashInterface *);
uint FlashInterface_TellFlashTypeOn(FlashInterface *,int,int);
uint FlashInterface_DoMsgPage(FlashInterface *);
uint FlashInterface_DoMsg(FlashInterface *,int,float,int);
uint FlashInterface_GetMsgLine(FlashInterface *,int,int,char const **);
uint FlashInterface_FindMsg(FlashInterface *,int,char const ***,int *);
uint FlashInterface_CmpMsgs(FlashInterface *,void const *,void const *);
uint FlashInterface_ParseMsgFile(FlashInterface *,int,char *,int,int);
uint FlashInterface_ReadMsgText(FlashInterface *);
uint FlashInterface_CancelMsg(FlashInterface *,int);
uint FlashInterface_PerFrame(FlashInterface *);
uint FlashInterface_SendEvtMsgDone(FlashInterface *,int);
uint FlashInterface_MsgMenuCheck(FlashInterface *);
uint FlashInterface_SimKeyEvent(FlashInterface *);
uint FlashInterface_CommandResult(FlashInterface *,int);
uint FlashInterface_SetCamera(FlashInterface *,char const *);
uint FlashInterface_Command(FlashInterface *,char const *,char const *,int);
uint FlashInterface_FloatArg(FlashInterface *,char const **,float);
uint FlashInterface_IntArg(FlashInterface *,char const **,int);
uint FlashInterface_StringArg(FlashInterface *,char const **,char *);
uint FlashInterface_ResetSettableStrings(FlashInterface *);
uint FlashInterface_StopAllSounds(FlashInterface *);
uint FlashInterface_PlaySound(FlashInterface *,int,char const *);
uint FlashInterface_SetVariable(FlashInterface *,char const *,int,void const *);
uint FlashInterface_GetVariable(FlashInterface *,char const *,int *,void **);
uint FlashInterface_LookupVariable(FlashInterface *,char const *);
uint FlashInterface_GetCurrentSpriteInstance(FlashInterface *);
uint FlashInterface_FindClient(FlashInterface *,char const *);
uint FlashInterface_RemoveClient(FlashInterface *,char const *);
uint FlashInterface_AddClient(FlashInterface *,char const *);
uint FlashInterface_FindMemoryCardImages(FlashInterface *,char const *);
uint FlashInterface_MemoryCardClearImages(FlashInterface *);
uint FlashInterface_MemoryCardSetImages(FlashInterface *,int *);
// uint FlashInterface_MemoryCardImageWadContext(wadContext *);
// uint FlashInterface_ReplaceTexture(F_Shape *,renTexture *);
// uint FlashInterface_GrabTexture(F_Shape *);
// uint FlashInterface_FindDynamicShapes(renFlashClient *);
uint FlashInterface_ResetShortTerm(void);
uint FlashInterface_ResetVars(void);
uint FlashInterface_OneTimeSetup(void);
uint FlashInterface_Destructor_FlashInterface(void);
uint FlashInterface_FlashInterface(void);
// uint FlashInterface_AddVar(int,char const *,int,void *,void (FlashInterface_*)(FlashInterface *,FlashInterface_fvEntry const *));
uint FlashInterface_HashFindAvailable(char const *);
uint FlashInterface_HashFind(char const *);
uint FlashInterface_Hash(char const *);
uint FlashInterface_SetSoundMode(int);
uint FlashInterface_SetProgressiveScan(int);
uint FlashInterface_SetWideScreen(int);
uint FlashInterface_SetVibration(int);
uint FlashInterface_SetSoundVolume(int);
uint FlashInterface_SetMusicVolume(int);
uint FlashInterface_SetZoneVars(int);
// uint FlashInterface_SF_Zone_Choice(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_FOV(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_OverUnder(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_DropShadowOffset(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_DropShadowColor(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_SoundMode(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_ProgressiveScan(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_WideScreen(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_Vibration(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_Volume(FlashInterface_fvEntry const *);
// uint FlashInterface_SF_Sound(FlashInterface_fvEntry const *);
extern uint FlashInterface_msgFile;
extern uint FlashInterface_vtbl;
extern FlashInterface *flashInterface;


#endif