#ifndef GOAI_H
#define GOAI_H

#include "structs.h"


// uint goAI_GetFlightHeight(void);
// uint goAI_IsCulled(void);
// uint goAI_IsCreatureDead(void);
// uint goAI_GetTargetCreature(void);
// uint goAI_GetTarget(void);
// uint goAI_CallbackData_CallbackData(void);
// uint goAI_HideHealthMeter(void);
// uint goAI_ShowHealthMeter(void);
// uint goAI_AdjustStuckOffset(void);
// uint goAI_GetDamageMultiplier(int);
// uint goAI_GetNextSitePos(void);
// uint goAI_CalculateTargetLastSeenSite(VUVec4,VUMat4 const *);
// uint goAI_IsOutsideSafeZone(void);
// uint goAI_TriggerFrozenMove(void);
// uint goAI_TriggerWorldIdleMove(void);
// uint goAI_UpdateFrozen(void);
// uint goAI_Unfreeze(int);
// uint goAI_RemoveWadContext(wadContext *);
// uint goAI_CalculatePath(ushort,ushort);
// uint goAI_CancelMoveByName(uint);
// uint goAI_ForceMoveByName(uint,int);
// uint goAI_SetTarget(goHandle);
// uint goAI_RemoveCurrentAction(void);
// uint goAI_CollisionCallback(goGameObject *,void *);
// uint goAI_EnemySightCallback(void);
// uint goAI_UpdatePerceptionDisk(goCreature *,int);
// uint goAI_UpdatePerceptionNoDisk(goCreature *,int);
// uint goAI_CanSeePosition(VUVec4);
// uint goAI_FindNewTargets(void);
// uint goAI_UpdatePerception(goCreature *,int);
// uint goAI_CheckStatesAndCaps(goCreature *);
// uint goAI_CheckStates(goCreature *);
// uint goAI_CallbackData_CheckTargetSight(float,goHandle);
// uint goAI_Alert(void);
// uint goAI_AlertCallback(void);
// uint goAI_SetupPerception(void);
// uint goAI_UpdateSeekTargetMode(void);
// uint goAI_UpdateSeekSiteMode(void);
// uint goAI_EnterSeekTarget(void);
// uint goAI_EnterSeekSite(void);
// uint goAI_EnterReaquire(void);
// uint goAI_EnterPatrol(short);
// uint goAI_EnterWander(void);
// uint goAI_ReturnToStartSite(int);
// uint goAI_Update(void);
// uint goAI_IgnoreMode(void);
// uint goAI_SetIgnoreMode(void);
// uint goAI_UpdateGrid(void);
// uint goAI_UpdateForceMoveMode(void);
// uint goAI_CullCheck(void);
// uint goAI_UpdateFromTweaks(void);
// uint goAI_SendEventTarget(goHandle);
// uint goAI_SendEventTargetDie(void);
// uint goAI_UpdateReaquireMode(void);
// uint goAI_EndOfPatrol(void);
// uint goAI_UpdatePatrolMode(void);
// uint goAI_UpdateSearchMode(void);
// uint goAI_CalculateTarget(VUVec4,VUVec4 *,VUVec4 *,int,VUMat4 const *);
// uint goAI_CalculateTargetClimbing(float,VUVec4,float,VUVec4 *,VUVec4 *,int,VUMat4 const *);
// uint goAI_CalculateTargetStrafing(float,VUVec4,float,VUVec4 *,VUVec4 *,int);
// uint goAI_GetTravelDistance(VUVec4,float *,VUVec4 *,VUVec4 *,VUVec4 *);
// uint goAI_CalculateJumping(float);
// uint goAI_UpdateReturnToStartMode(void);
// uint goAI_UpdateStandMode(void);
// uint goAI_UpdateWanderMode(void);
// uint goAI_Init(goClient *,int,uint,signed char);
// uint goAI_SurroundTarget(goCreature *);
// uint goAI_SetControls(VUVec4,VUVec4,VUVec4);
// uint goAI_CalculateSecondRadius(goCreature *,float);
// uint goAI_SurroundTargetLadderRope(VUVec4 *,VUVec4 *,VUVec4,VUVec4);
// uint goAI_InsideDiskSurroundTarget(tValidityDisk const *,VUVec4 *,VUVec4 *,VUVec4,VUVec4,float,float);
// uint goAI_GoToGridHole(tValidityDisk const *,VUVec4 *,VUVec4 *,VUVec4,VUVec4,float);
// uint goAI_GotoNearestWaypoint(VUVec4 *,VUVec4 *,VUVec4,VUMat4 const *);
// uint goAI_GotoWaypoint(VUVec4 *,VUVec4 *,ushort,VUMat4 const *,float);
// uint goAI_RunSlot(void);
// uint goAI_TriggerCurrentActionBranch(tFightSystem *);
// uint goAI_EnterDead(void);
// uint goAI_GetFight(void);
// uint goAI_SetFight(Fight *);
// uint goAI_Damage(int);
// uint goAI_ResetPosition(void);
// uint goAI_DoCancelAllMoves(void);
// uint goAI_QuickBlock_Chance(goCreature *,float);
// uint goAI_QuickBlock_HitFlags(goCreature *,uint);
// uint goAI_QuickBlock_Context(goCreature *,int);
// uint goAI_QuickBlock_Move(goCreature *,dc_tMove const *);
// uint goAI_QuickBlock(goGameObject *,dc_tMove const *,int,uint);
// uint goAI_CheckStuck(VUVec4,VUVec4);
// uint goAI_SetNextSite(int,int);
// uint goAI_CalculateOffset_(float);
// uint goAI_CalculateOffset(float,VUVec4);
// uint goAI_CanAttack(void);
// uint goAI_InitPerception(void);
// uint goAI_Destructor_goAI(void);
uint goAI_goAI(uint a0);
// uint goAI_InitPaths(void);
// uint goAI_sm_iPaths;
// uint goAI_sm_iNumPaths;
// uint goAI_vtbl;


#endif