#ifndef GOPLAYER_H
#define GOPLAYER_H

#include "structs.h"


uint goPlayer_ClrFlags(uint);
uint goPlayer_TstFlags(uint);
uint goPlayer_SetFlags(uint);
uint goPlayer_GetCostumeTweaks(goPlayer *);
uint goPlayer_StateData_StateData(goPlayer *);
uint goPlayer_InFight(goPlayer *);
uint goPlayer_ResetMash(goPlayer *);
uint goPlayer_MashInput(int);
// uint goPlayer_GetJoystickZone(int,sysPad const *,float);
uint goPlayer_CalcZoneTarget(goPlayer *);
uint goPlayer_HideCameraTarget(goPlayer *);
uint goPlayer_ShowCameraTarget(goPlayer *);
uint goPlayer_AddCameraTarget(goPlayer *);
uint goPlayer_RemoveCameraTarget(goPlayer *);
uint goPlayer_ShowMeterBar(goPlayer *);
uint goPlayer_EnoughMagicPoints(float);
uint goPlayer_SubtractMagicPoints(float);
uint goPlayer_MoveTrackData_Update(float);
uint goPlayer_MoveTrackData_GetContextCount(short);
// uint goPlayer_MoveTrackData_GetMoveCount(dc_tMove const *);
uint goPlayer_MoveTrackData_AddContext(short);
// uint goPlayer_MoveTrackData_AddMove(dc_tMove const *);
uint goPlayer_MoveTrackData_MoveTrackData(goPlayer *);
uint goPlayer_Run(int);
uint goPlayer_HandleBodyTrail(goPlayer *);
// uint goPlayer_UpdateSavePoint(int,VUVec4,renMaterial *);
uint goPlayer_HandleUseWorld(goPlayer *);
uint goPlayer_SetStateData(void const *);
uint goPlayer_GetStateData(void *);
// uint goPlayer_CheckFirstTime(goPlayer_FT_TYPE);
uint goPlayer_SetPowerUpPoints(uint);
uint goPlayer_GetDamageMultiplier(int);
uint goPlayer_EnableBladeLights(int);
uint goPlayer_CancelMoveByName(uint);
uint goPlayer_ForceMoveByName(uint,int);
uint goPlayer_HandleLowHealthSound(goPlayer *);
uint goPlayer_PopBank(char const *);
uint goPlayer_PushBank(char const *);
uint goPlayer_SetWeaponAttachment(goPlayer *);
uint goPlayer_HandleSubWeapon(goPlayer *);
uint goPlayer_HideSubWeapon(uint);
uint goPlayer_ShowSubWeapon(uint);
uint goPlayer_DisableSubWeapon(int);
uint goPlayer_EnableSubWeapon(int);
uint goPlayer_HandleHitCounter(goPlayer *);
// uint goPlayer_GiveBonus(dc_tBonus const *);
// uint goPlayer_IncHitCounter(goGameObject *,float);
uint goPlayer_AddGodMeter(float,int);
uint goPlayer_HandleHermesMode(goPlayer *);
// uint goPlayer_SetHermesLineOfSight(goHandle);
uint goPlayer_UpdateReticle(goPlayer *);
uint goPlayer_HandleGodMode(goPlayer *);
uint goPlayer_FindGrappleTarget(goPlayer *);
// uint goPlayer_FindAllTargetsAroundPlayer(float,uint,goCreature *,int);
// uint goPlayer_FindAllTargets(VUVec4,float,uint,goCreature *,int);
uint goPlayer_GetTargetJoint(int);
uint goPlayer_GetTarget(int);
uint goPlayer_FindAllTargetsCallback(goPlayer *);
// uint goPlayer_FindTargetManual(goHandle,float);
// uint goPlayer_FindTargetManualCallback(goGameObject *,void *);
// uint goPlayer_GetDirToTarget(goHandle,VUVec4,VUVec4);
// uint goPlayer_FindTarget(goHandle,int,float);
uint goPlayer_FindTargetCallback(goPlayer *);
// uint goPlayer_IsSphereOnScreen(VUVec4);
uint goPlayer_SetHermesMeterLevel(int);
uint goPlayer_SetMagicMeterLevel(int);
uint goPlayer_SetHealthMeterLevel(int);
uint goPlayer_ProcessPickup(uint,uint);
uint goPlayer_AcquireAllPickups(goPlayer *, int);
uint goPlayer_IsPickupEnabled(int *);
uint goPlayer_GetPickupLevel(uint);
uint goPlayer_MaxPickupCount(uint);
uint goPlayer_GetPickupCount(uint);
uint goPlayer_DecPickup(uint,uint,uint);
uint goPlayer_IncPickup(uint,uint,uint);
uint goPlayer_HandleWiggle(goPlayer *);
uint goPlayer_HandleValidityDisk(goPlayer *);
uint goPlayer_HandleTargeting(goPlayer *);
uint goPlayer_VisibilityCallback(goPlayer *);
uint goPlayer_HandlePlayerControlVector(goPlayer *);
uint goPlayer_HandlePlayerControls(goPlayer *);
uint goPlayer_SelectMagic(int,char const *);
uint goPlayer_HandlePickups(goPlayer *);
uint goPlayer_HandleUpgrades(goPlayer *);
uint goPlayer_AddOrbPoints(float,float,float,float);
uint goPlayer_HandleUrns(goPlayer *);
uint goPlayer_UpdateOrbData(goPlayer *);
uint goPlayer_ResetFlash(goPlayer *);
uint goPlayer_UpdateFlashPickups(goPlayer *);
uint goPlayer_UpdateFlash(goPlayer *);
// uint goPlayer_RemoveWadContext(wadContext const *);
uint goPlayer_Destructor_goPlayer(goPlayer *);
uint goPlayer_goPlayer(goPlayer *);
uint goPlayer_ResetShortTerm(goPlayer *);
uint goPlayer_Reset(goPlayer *);
uint goPlayer_ReInit(goPlayer *);
uint goPlayer_FeedBacktoEOGPS(goPlayer *);
// uint goPlayer_Init(goClient *);
extern uint goPlayer_sm_uFlags;
extern uint goPlayer_sm_MTD;
extern uint goPlayer_state;
extern uint goPlayer_vtbl;
extern uint goPlayer_sm_pCameraTarget;
extern goPlayer *goPlayer_sm_pPlayer;


#endif