#ifndef GOSOLDIER_H
#define GOSOLDIER_H

#include "structs.h"


// uint goSoldier_GetFreezeTimeLeft(float);
// uint goSoldier_UsingAnimDrivenMotion(void);
// uint goSoldier_Strafing(void);
// uint goSoldier_SetImpulse(VUVec4,int);
// uint goSoldier_GetRope(void);
// uint goSoldier_GetGOName(void);
// uint goSoldier_IsFrozen(void);
// uint goSoldier_GetFrozenRatio(void);
// uint goSoldier_GetRadius(void);
// uint goSoldier_GetHeight(void);
// uint goSoldier_GetMass(void);
// uint goSoldier_GetEffectSystem(void);
// uint goSoldier_GetHandleSystem(void);
// uint goSoldier_GetAttachmentSystem(void);
// uint goSoldier_GetAnimSystem(void);
// uint goSoldier_GetCreatureControls(void);
// uint goSoldier_CanDoCombatMove(void);
// uint goSoldier_DerivedTweaks(void);
// uint goSoldier_GetFirstNavBankMotionP(void);
// uint goSoldier_GetNavBranch(dc_tNavBankBase const *,int);
// uint goSoldier_SetTweaks(dc_tCreature const *);
// uint goSoldier_SetDamageInfo(float,VUVec4,uint,int);
// uint goSoldier_DoFeetIK(VUVec4);
// uint goSoldier_InitFeetIK(char const *,int);
// uint goSoldier_UpdateDead(void);
// uint goSoldier_PostSoldierUpdate(void);
// uint goSoldier_Update(uint);
// uint goSoldier_DoNormalMotion(VUVec4,VUVec4,VUVec4,int,int *,float);
// uint goSoldier_DoStrafeMotion(VUVec4,VUVec4,VUVec4,int *,float);
// uint goSoldier_HandleTrapDamage(float);
// uint goSoldier_HandleWalkingSlidingFalling(VUVec4,float);
// uint goSoldier_HandleCollisionOnly(VUVec4,int,int,int,float);
// uint goSoldier_HandleJumping(float);
// uint goSoldier_Do180Flip(void);
// uint goSoldier_SetMode_DoubleJumping(void);
// uint goSoldier_SetMode_Jumping(void);
// uint goSoldier_SetMode_Sliding(void);
// uint goSoldier_SetMode_OnCeiling(void);
// uint goSoldier_SetMode_OnGround_Landing_(void);
// uint goSoldier_SetMode_OnGround_Landing(VUVec4);
// uint goSoldier_SetMode_OnGround(void);
// uint goSoldier_SetMode_Falling(uint,float);
// uint goSoldier_UpdateImpulse(float);
// uint goSoldier_UpdateFreezing(void);
// uint goSoldier_BreakFrozenIncarnation(int);
// uint goSoldier_CreateFrozenIncarnation(void);
// uint goSoldier_UpdateTimeScale(void);
// uint goSoldier_GetTargetingPos(int);
// uint goSoldier_Destructor_goSoldier(void);
// uint goSoldier_Enable(void);
// uint goSoldier_Disable(void);
// uint goSoldier_DestroyFightSystem(void);
// uint goSoldier_goSoldier(goClient *,dc_tCreature const *,tEffectSystem *,int);
// uint goSoldier_Init(dc_tCreature const *,tEffectSystem *);
// uint goSoldier_SetSaveData(uchar);
// uint goSoldier_SetAttachmentSaveData(int);
// uint goSoldier_ClearVelocity(void);
// uint goSoldier_Warp(VUMat4 const *);
// uint goSoldier_RemoveWadContext(wadContext *);
// uint goSoldier_Reset(uint);
// uint goSoldier_ResetLightSoldier(void);
// uint goSoldier_RunLightSoldier(void);
// uint goSoldier_ResetStatue(void);
// uint goSoldier_SetInstanceVariations(float,float,uint);
// uint goSoldier_UpdateVarsFromTweakers(void);
// uint goSoldier_SetDynamicNavCollision(void);
// uint goSoldier_SetNavCollision(void);
// uint goSoldier___dl(void *);
// uint goSoldier_Allocate(wadContext *);
// uint goSoldier_DoDriftingMotion(VUVec4,VUVec4,VUVec4,float);
// uint goSoldier_HandleDrifting(float);
// uint goSoldier_ResetDriftTimer(void);
// uint goSoldier_CancelDriftWings(void);
// uint goSoldier_SetMode_Drifting(void);
// uint goSoldier_DetachFromGrapple(void);
// uint goSoldier_HandleJumpingDuringGrapple(VUVec4,VUVec4);
// uint goSoldier_SetMode_Grapple(void);
// uint goSoldier_ResolvePhysicalOrientationDuringGrapple(VUVec4,float);
// uint goSoldier_InitGrappleMotion(void);
// uint goSoldier_DoGrappleMotion(VUVec4,VUVec4,float);
// uint goSoldier_ConvertGrappleToPOR(VUVec4,VUVec4);
// uint goSoldier_ConvertPORToGrapple(VUVec4,VUVec4);
// uint goSoldier_FlyingGroundChecks(VUVec4);
// uint goSoldier_SetMode_Flying(void);
// uint goSoldier_HandleWaterSurfaceCollisionOnly(VUVec4);
// uint goSoldier_DoInTheWaterMotion(VUVec4,VUVec4,float);
// uint goSoldier_DivingChecks(VUVec4,float);
// uint goSoldier_InTheWaterGroundChecks(VUVec4);
// uint goSoldier_HandleSwimmingAndDiving(VUVec4,float);
// uint goSoldier_ResolvePhysicalOrientationInWater(VUVec4,float);
// uint goSoldier_CheckForDiveIntoWater(VUVec4,float,float);
// uint goSoldier_SetMode_DiveIntoWater(float);
// uint goSoldier_SetMode_Diving(void);
// uint goSoldier_SetMode_Underwater(void);
// uint goSoldier_SetMode_Floating(void);
// uint goSoldier_DetachFromCeiling(void);
// uint goSoldier_DetachFromWall(void);
// uint goSoldier_DoWallAnimation(float,float *,float *,float *,float *);
// uint goSoldier_DoWallMotion(VUVec4,VUVec4,VUVec4,float);
// uint goSoldier_ClimbingGroundChecks(VUVec4,int);
// uint goSoldier_HandleClimbingAndWallHang(VUVec4,VUVec4,float,int);
// uint goSoldier_HandleJumpingFacingAWall(float);
// uint goSoldier_PerformPullup(void);
// uint goSoldier_SetMode_WallHang(void);
// uint goSoldier_SetMode_Climbing(int);
// uint goSoldier_DoOnARopeMotion(VUVec4,VUVec4,VUVec4,float);
// uint goSoldier_HandleHangTargets(uint);
// uint goSoldier_HandleWalkingSlidingFalling_OnARope(VUVec4,float);
// uint goSoldier_HandleJumpingOnARope(VUVec4,VUVec4,float);
// uint goSoldier_ResolvePhysicalOrientationOnARope(VUVec4,float);
// uint goSoldier_SetMode_OnARope(void);
// uint goSoldier_UpdateRope(void);
// uint goSoldier_DetachFromRope(int);
// uint goSoldier_AttachToRope(goHandle,float);
// uint goSoldier_DoAttachedToMotion(VUVec4,float);
// uint goSoldier_DoHaveAttachedMotion(VUVec4,VUVec4,float);
// uint goSoldier_HandleInteractiveObjects(VUVec4);
// uint goSoldier_FindIOCreature(void);
// uint goSoldier_SetMode_OnGround_HaveAttached(void);
// uint goSoldier_SetMode_HaveAttached(goCreature *,VUVec4,VUVec4,int,int);
// uint goSoldier_BalanceGroundChecks(VUVec4,float);
// uint goSoldier_HandleBalanceWalk(void);
// uint goSoldier_sm_goSoldierMultiPool;
// uint goSoldier_vtbl;
// uint goSoldier_s_wLightFrameOddCount;
// uint goSoldier_s_wLightFrameEvenCount;


#endif