#ifndef GOSOLDIERIO_INTERNAL_H
#define GOSOLDIERIO_INTERNAL_H

#include "structs.h"


uint goSoldierIO_Internal_FindCallback(void);
uint goSoldierIO_Internal_iHandleIndex;
uint goSoldierIO_Internal_iIOCJoint;
uint goSoldierIO_Internal_pInteractiveCreature;
uint goSoldierIO_Internal_pInteractiveObject;
uint goSoldierIO_Internal_vEndPos;
uint goSoldierIO_Internal_vHandTestPosIO;
uint goSoldierIO_Internal_vInteractiveObjectPos;
uint goSoldierIO_Internal_vIOCForward;
uint goSoldierIO_Internal_vIOCOffset;
uint goSoldierIO_Internal_vIOForward;


#endif