#ifndef HFSM_BALANCEGEOM_H
#define HFSM_BALANCEGEOM_H

#include "structs.h"


uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_SInitial_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_SInitial_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_SInitial_SInitial(HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_ProcessEvent(bhvrHFSMClient *,goEvent const *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_CallExitCode(hfsmState *,bhvrHFSMClient *,goEvent const *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_hfsmBalanceGeom(void);
uint HFSM_BalanceGeom_HFSMCreator_GetDataSize(void);
uint HFSM_BalanceGeom_hfsmBalanceGeom_Destructor_hfsmBalanceGeom(void);
uint HFSM_BalanceGeom_HFSMCreator_HFSMCreator(void);
uint HFSM_BalanceGeom_hfsmBalanceGeom___dl(void *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_Allocate(wadContext *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_GetStartState(bhvrHFSMClient *,goEvent const *);
uint HFSM_BalanceGeom_HFSMCreator_GetDependantClass(int);
uint HFSM_BalanceGeom_HFSMCreator_GetNumDependantClasses(void);
uint HFSM_BalanceGeom_HFSMCreator_GetName(void);
uint HFSM_BalanceGeom_HFSMCreator_Create(void);
uint HFSM_BalanceGeom_GetParam(bhvrHFSMClient *);
uint HFSM_BalanceGeom_hfsmBalanceGeom_sm_hfsmBalanceGeomMultiPool;
uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_SInitial_vtbl;
uint HFSM_BalanceGeom_hfsmBalanceGeom_SBalanceGeom_vtbl;
uint HFSM_BalanceGeom_HFSMCreator_vtbl;
uint HFSM_BalanceGeom_hfsmBalanceGeom_vtbl;


#endif